version: '3'
services:
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    networks:
      - loki-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana  # Persist Grafana data
    networks:
      - loki-network
    depends_on:
      - loki

volumes:
  loki-data:
  grafana-data:

networks:
  loki-network:
    driver: bridge
